- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml


- name: copy the mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongod client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: content to mongod catalogue
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: load products into mongod
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml

