- name: create roboshop user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop system user
    system: true
    shell: /sbin/nologin
    home: /app

- name: remove directory
  ansible.builtin.file:
      path: /app
      state: absent

- name: create directory
  ansible.builtin.file:
      path: /app
      state: directory

- name: remove the code
  ansible.builtin.file:
      path: /tmp/{{ component }}.zip
      state: absent
  
- name: dwonload the file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
    dest: /tmp/{{ component }}.zip

- name: extract the {{ component }} appilication
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes