- name: "copy the {{component }} service"
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon reload

- name: enable and start
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: true
